### ISSUE TITLE
java.lang.NoSuchMethodException: com.github.config.MainConfig$$EnhancerBySpringCGLIB

### ISSUE THREAD

**Issue by hbsndg** [Wechat-Group/weixin-java-tools-springmvc#7]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	... 22 more
Caused by: java.lang.NoSuchMethodException: com.github.config.MainConfig$$EnhancerBySpringCGLIB$$806da349.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getDeclaredConstructor(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 23 more

**Comment by binarywang** [comment]
从错误信息上看是因为MainConfig没有默认无参构造方法，可能是你使用的框架要求其必须有默认无参构造方法，因此你自己加入即可。

**Comment by bryce-ma** [comment]
#9
